backend:
name: git-gateway
branch: main # Default branch in GitHub

media_folder: "image" # Where uploaded images are saved in GitHub
public_folder: "/image" # How the browser accesses those images

collections:
- name: "products"
label: "Products"
folder: "content/products" # Folder storing individual product entries
create: true
slug: "{{slug}}"
fields:
- { label: "Title", name: "title", widget: "string" }
- { label: "Price", name: "price", widget: "string" }
- { label: "Image", name: "image", widget: "image" }
- { label: "Description", name: "body", widget: "markdown" }

